version: '3'
services:
  spark-slave:
    image: diasspark
    entrypoint: /bin/bash -c "service ssh restart && /root/spark-2.2.1-bin-hadoop2.7/sbin/start-slave.sh spark://spark-master:7077 && sleep infinity"
    depends_on:
      - spark-master
  spark-master:
    image: diasspark
    entrypoint: /bin/bash -c "service ssh restart && /root/spark-2.2.1-bin-hadoop2.7/sbin/start-master.sh && sleep infinity"
    ports:
      - 8080:8080
      - 7077:7077
