version: '3'
services:
  hadoop-master:
    image: diashadoop-master
    environment:
     - MASTER_SCRIPT=master.sh
    volumes:
     - ./workloads:/root/workloads
     - ./jars:/root/jars
     - ./scripts:/root/scripts
    depends_on:
      - hadoop-slave
  hadoop-slave:
    image: diashadoop
